# Generated by Django 5.1 on 2024-12-29 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0003_alter_item_item1_alter_item_item2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synergy',
            name='sequence',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champion',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
