# Generated by Django 5.1 on 2024-09-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0004_item_remove_lolmetachampion_item_alter_synergy_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kor_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
