# Generated by Django 5.1 on 2024-12-30 00:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0004_synergy_sequence_alter_champion_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synergy',
            name='sequence',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
