# Generated by Django 5.1 on 2024-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0005_item_kor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kor_item1',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='kor_item2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
