# Generated by Django 5.1 on 2024-12-30 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0005_alter_synergy_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='kor_item1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kor_item2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kor_name',
        ),
    ]
