# Generated by Django 5.1 on 2024-09-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0006_item_kor_item1_item_kor_item2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Augmenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('effect', models.CharField(max_length=500)),
                ('tier', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='lolmeta',
            name='augmenter',
            field=models.ManyToManyField(to='Meta.augmenter'),
        ),
        migrations.CreateModel(
            name='AugmenterImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=255)),
                ('augmenter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Meta.augmenter')),
            ],
        ),
    ]
