# Generated by Django 5.1 on 2024-10-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0007_augmenter_lolmeta_augmenter_augmenterimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
