# Generated by Django 5.1 on 2024-10-11 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0008_remove_comment_writer_alter_comment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(default=False)),
                ('lol_meta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meta.lolmeta')),
            ],
        ),
    ]
