# Generated by Django 5.1 on 2024-10-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0010_comment_writer_metareaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolmeta',
            name='reroll_lv',
            field=models.IntegerField(default=0),
        ),
    ]
