# Generated by Django 5.1 on 2024-11-09 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0011_lolmeta_reroll_lv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lolmeta',
            name='win_rate',
        ),
    ]
