# Generated by Django 5.1 on 2024-11-18 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meta', '0012_remove_lolmeta_win_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='item1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='item2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='kor_item1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='kor_item2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='kor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
